# Generated by Django 4.1.7 on 2023-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_added',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
