# Generated by Django 4.1.7 on 2023-05-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0004_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Referals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_user', to=settings.AUTH_USER_MODEL)),
                ('refered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
