# Generated by Django 4.1.7 on 2023-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0005_customuser_referal_active_customuser_referal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referal_count',
            field=models.IntegerField(default=0),
        ),
    ]
