# Generated by Django 4.1.7 on 2023-04-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_categoryoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffers',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffers',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
