# Generated by Django 4.1.7 on 2023-04-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_amount_orders_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='strap_material',
        ),
    ]
