# Generated by Django 4.1.7 on 2023-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variations_variation_category_and_more'),
        ('orders', '0003_remove_orderproduct_strap_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variaton',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variaton',
            field=models.ManyToManyField(blank=True, to='products.variations'),
        ),
    ]
