# Generated by Django 4.1.7 on 2023-04-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_variaton_orderproduct_varition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='varition',
            new_name='variation',
        ),
    ]
