# Generated by Django 4.1.7 on 2023-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mrp', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/products')),
                ('is_avaliable', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='products', to='categories.category')),
            ],
        ),
    ]
