# Generated by Django 4.1.7 on 2023-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='variation_category',
        ),
        migrations.AlterField(
            model_name='variations',
            name='variation_value',
            field=models.CharField(choices=[('Leather', 'Leather'), ('Rubber', 'Rubber'), ('Metal', 'Metal')], max_length=100),
        ),
    ]
