# Generated by Django 4.1.7 on 2023-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_offer',
            field=models.BooleanField(default=False),
        ),
    ]
